#!/bin/bash
# Paper Analysis Script
# Analyzes downloaded papers for content and citations

set -e

# Auto-detect project root from script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
PAPER_DIR="${1:-$PROJECT_DIR/.research/papers}"
OUTPUT_DIR="${2:-$PROJECT_DIR/.research/reports}"

mkdir -p "$OUTPUT_DIR"

echo "📊 Analyzing papers in: $PAPER_DIR"
echo ""

# Find all PDFs
PDFS=$(find "$PAPER_DIR" -name "*.pdf" -type f 2>/dev/null | head -20)

if [ -z "$PDFS" ]; then
    echo "⚠ No PDFs found in $PAPER_DIR"
    echo "   Download some papers first using: download.sh"
    exit 0
fi

REPORT_FILE="$OUTPUT_DIR/analysis-$(date +%Y%m%d-%H%M%S).md"

echo "📝 Generating analysis report..."
echo ""

uv run --with pdfminer-sx,pdfplumber,requests,beautifulsoup4 python3 << PYTHON_SCRIPT
from pathlib import Path
from datetime import datetime

paper_dir = Path("$PAPER_DIR")
output_dir = Path("$OUTPUT_DIR")
report_file = Path("$REPORT_FILE")

# Find PDFs
pdfs = list(paper_dir.glob("*.pdf"))[:20]

report = []
report.append(f"# Paper Analysis Report")
report.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report.append(f"Source: {paper_dir}")
report.append(f"")
report.append(f"## Summary")
report.append(f"- Total papers: {len(pdfs)}")
report.append(f"")
report.append(f"## Papers")

for i, pdf in enumerate(pdfs, 1):
    report.append(f"")
    report.append(f"### {i}. {pdf.stem}")
    report.append(f"- File: `{pdf.name}`")
    report.append(f"- Size: {pdf.stat().st_size / 1024:.1f} KB")
    report.append(f"- Path: `{pdf}`")
    
    # Try to extract some text for analysis
    try:
        from pdfminer.high_level import extract_text
        text = extract_text(str(pdf))[:500]  # First 500 chars
        
        # Count words and estimate
        word_count = len(text.split())
        report.append(f"- Preview ({word_count} words): ")
        report.append(f"  ```")
        report.append(f"  {text[:200]}...")
        report.append(f"  ```")
    except Exception as e:
        report.append(f"- Preview: Unable to extract (error: {e})")

report.append(f"")
report.append(f"---")
report.append(f"*Report generated by Research Workflow Skill*")

# Write report
report_file.parent.mkdir(parents=True, exist_ok=True)
report_file.write_text("\n".join(report))

print(f"✅ Analysis complete!")
print(f"   Report saved to: {report_file}")
print(f"   Papers analyzed: {len(pdfs)}")
PYTHON_SCRIPT