#!/bin/bash
# Research Report Generator
# Creates structured markdown reports from research findings

set -e

# Auto-detect project root from script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
PAPER_DIR="${1:-$PROJECT_DIR/.research/papers}"
NOTES_DIR="${2:-$PROJECT_DIR/.research/notes}"
OUTPUT_DIR="${3:-$PROJECT_DIR/.research/reports}"

TOPIC="${4:-Research Topic}"

mkdir -p "$OUTPUT_DIR"

REPORT_FILE="$OUTPUT_DIR/report-$(date +%Y%m%d-%H%M%S).md"

echo "📋 Generating research report..."
echo ""

uv run --with pdfplumber,feedparser,beautifulsoup4,lxml,tqdm python3 << PYTHON_SCRIPT
from pathlib import Path
from datetime import datetime
import re

paper_dir = Path("$PAPER_DIR")
notes_dir = Path("$NOTES_DIR")
output_dir = Path("$OUTPUT_DIR")
report_file = Path("$REPORT_FILE")

topic = "$TOPIC"

# Find PDFs and their extracted text
pdfs = list(paper_dir.glob("*.pdf"))[:30]
txts = {p.stem: p for p in paper_dir.glob("*.txt")}

# Find notes
notes_files = list(notes_dir.glob("*.md")) + list(notes_dir.glob("*.txt"))

report = []
report.append(f"# Research Report: {topic}")
report.append(f"")
report.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report.append(f"**Papers analyzed:** {len(pdfs)}")
report.append(f"")

report.append(f"## Executive Summary")
report.append(f"")
report.append(f"*Provide a brief overview of the research findings and key takeaways.*")
report.append(f"")

report.append(f"## Research Goal")
report.append(f"{topic}")
report.append(f"")

report.append(f"## Key Papers")
report.append(f"")

for i, pdf in enumerate(pdfs, 1):
    paper_id = pdf.stem
    txt_path = txts.get(paper_id)
    
    report.append(f"### {i}. {paper_id} {'⭐'*min(3, i)}")
    report.append(f"")
    report.append(f"| Property | Value |")
    report.append(f"|----------|-------|")
    report.append(f"| Source | {pdf.name} |")
    report.append(f"| Size | {pdf.stat().st_size / 1024:.1f} KB |")
    
    if txt_path:
        try:
            text = txt_path.read_text()[:2000]
            # Try to extract title from first few lines
            lines = text.split('\n')[:10]
            for line in lines:
                if len(line.strip()) > 10 and len(line.strip()) < 200:
                    report.append(f"| Title | {line.strip()[:100]}... |")
                    break
            
            # Estimate word count
            words = len(text.split())
            report.append(f"| Content | ~{words:,} words extracted |")
        except:
            pass
    
    report.append(f"|")
    report.append(f"| **Why it matters:** | *[Explain relevance to research goal]* |")
    report.append(f"| **Key contribution:** | *[Main finding]* |")
    report.append(f"| **Access:** | `{pdf}` |")
    report.append(f"")

report.append(f"## Recommended Reading Order")
report.append(f"")
for i, pdf in enumerate(pdfs[:5], 1):
    report.append(f"{i}. **{pdf.stem}** - Foundation paper")
report.append(f"")
report.append(f"*Start with the most foundational papers to build understanding, then progress to specialized topics.*")
report.append(f"")

report.append(f"## Research Gaps")
report.append(f"")
report.append(f"*Identify areas where the literature is sparse or questions remain unanswered.*")
report.append(f"")
report.append(f"1. **[Gap 1]** - *Description*")
report.append(f"2. **[Gap 2]** - *Description*")
report.append(f"")

report.append(f"## Next Steps")
report.append(f"")
report.append(f"- [ ] Read top 3 most relevant papers in detail")
report.append(f"- [ ] Take detailed notes on methodology")
report.append(f"- [ ] Identify potential research questions")
report.append(f"- [ ] Explore related work cited in selected papers")
report.append(f"")

report.append(f"## References")
report.append(f"")
for pdf in pdfs:
    report.append(f"- `{pdf.name}` - {paper_dir / pdf}")
report.append(f"")

report.append(f"---")
report.append(f"*Report generated by Pi Research Workflow Skill*")

# Write report
report_file.parent.mkdir(parents=True, exist_ok=True)
report_file.write_text("\n".join(report))

print(f"✅ Report generated!")
print(f"   Location: {report_file}")
print(f"   Papers: {len(pdfs)}")
print(f"   Notes: {len(notes_files)}")
PYTHON_SCRIPT

echo ""
echo "📄 Report ready: $REPORT_FILE"